# Generated by Django 3.1.5 on 2021-01-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255, unique=True)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
